### ISSUE TITLE
能否简化一个复制输入内容到剪贴板的程序

### ISSUE THREAD

**Issue by Boblove12** [ij369/scanners-go#1]
你好V友，首先感谢您的付出。
目前您的程序可以实现将扫码结果转发到 http 服务器，能否帮忙写一个将扫码结果复制到剪贴板的程序（可以不需要web页面，或者集成到您已有的程序中）
再次感谢！

**Comment by ij369** [comment]
这位朋友你好，这个需求可以实现，基于现在目前的场景，写入剪切板并不是它的预期行为。

- 如果需要我增加这个功能，我需要知道你这个需求的使用场景，以及明确具体效果，例如：是使程序本身有这项功能，还是需要 Web 上扫码记录，点击记录进行拷贝？

- 还是说你想定制开发

**Comment by Boblove12** [comment]
感谢回复。
我的使用场景：工作中我需要不定期查询ems的邮寄结果并打印出来，需要在查询页码输入单号。
目前的问题是：在查询网页使用扫描器扫描单号，如果输入法是中文，会导致输入的结果出现中文（单号中英文字符），需要切换后再扫一次，所以需要一个能无视输入法，接收正确单号的脚本。使用您开发的这个程序后，我发现这个程序可以正确识别单号。

需要到剪贴板的原因：目前已有ahk脚本可以监控剪贴板，当发现符合规则的单号后，可以将单号作为网址的一部分直接打开网页，这样就可以直接扫描，脚本运行后就可以直接输出结果。

所以：
一、能否麻烦您在这个程序中添加一个复制结果到剪贴板的选项，这样我就可以凑合用。
二、也有定制的想法，但需要请您评估一下。已知：打开https://www.kuaidi100.com/chaxun?com=ems（快递公司代码）&nu=123456485（单号）可以直接打开快递的物流查询结果。
1.需要在扫描器检测到符合规则内容： XA加11位数字，如XA18975296812 XA16972351226 （非真实单号）,其中xa大小写不敏感；
2.构建链接 https://www.kuaidi100.com/chaxun?com=ems&nu=XA16972351226  其中链接中 nu= 后面就是单号；
3.检测D:\Program\browser\chrome.exe是否正在运行，如果没有运行，就用D:\Program\browser\chrome.exe打开第2步构建的链接，如果D:\Program\browser\chrome.exe已经运行中，在新标签中打开第2步构建的链接
再次感谢

**Comment by Boblove12** [comment]
进一步的定制设想：
已知：根据kuaidi100的技术文档，https://github.com/kuaidi100-api，可以直接发起查询并获取结果（返回类型可选json、html、text等）

设想：
1.开机启动scanners-go程序，当检测到快递单号（规则符合前述即可），如果配置页没有打开，那么用特定浏览器打开配置页，如果已经打开，那么直接转到打开的配置页；
2.在配置页中，使用kuaidi100的demo发送物流查询请求，获取html
3.在新标签中打开获取的html
再次感谢

**Comment by ij369** [comment]
是这样，我的这个程序目前只是方便后端开发。后续更新我会参考你给的场景，加上调用浏览器打开扫码内容的功能。因为扫码枪和回车键绑定，程序不做过滤，会有手动触发记录的几率，会导致频繁写入冗杂信息到系统的剪切板，所以目前没打算做。感谢关注，本次先暂时关闭 issue 了。

**Comment by ij369** [comment]
> 感谢回复。 我的使用场景：工作中我需要不定期查询ems的邮寄结果并打印出来，需要在查询页码输入单号。 目前的问题是：在查询网页使用扫描器扫描单号，如果输入法是中文，会导致输入的结果出现中文（单号中英文字符），需要切换后再扫一次，所以需要一个能无视输入法，接收正确单号的脚本。使用您开发的这个程序后，我发现这个程序可以正确识别单号。
> 
> 需要到剪贴板的原因：目前已有ahk脚本可以监控剪贴板，当发现符合规则的单号后，可以将单号作为网址的一部分直接打开网页，这样就可以直接扫描，脚本运行后就可以直接输出结果。
> 
> 所以： 一、能否麻烦您在这个程序中添加一个复制结果到剪贴板的选项，这样我就可以凑合用。 二、也有定制的想法，但需要请您评估一下。已知：打开[https://www.kuaidi100.com/chaxun?com=ems（快递公司代码）&nu=123456485（单号）可以直接打开快递的物流查询结果。](https://www.kuaidi100.com/chaxun?com=ems%EF%BC%88%E5%BF%AB%E9%80%92%E5%85%AC%E5%8F%B8%E4%BB%A3%E7%A0%81%EF%BC%89&nu=123456485%EF%BC%88%E5%8D%95%E5%8F%B7%EF%BC%89%E5%8F%AF%E4%BB%A5%E7%9B%B4%E6%8E%A5%E6%89%93%E5%BC%80%E5%BF%AB%E9%80%92%E7%9A%84%E7%89%A9%E6%B5%81%E6%9F%A5%E8%AF%A2%E7%BB%93%E6%9E%9C%E3%80%82) 1.需要在扫描器检测到符合规则内容： XA加11位数字，如XA18975296812 XA16972351226 （非真实单号）,其中xa大小写不敏感； 2.构建链接 https://www.kuaidi100.com/chaxun?com=ems&nu=XA16972351226 其中链接中 nu= 后面就是单号； 3.检测D:\Program\browser\chrome.exe是否正在运行，如果没有运行，就用D:\Program\browser\chrome.exe打开第2步构建的链接，如果D:\Program\browser\chrome.exe已经运行中，在新标签中打开第2步构建的链接 再次感谢

你好，以上功能已实现:
[releases](https://github.com/ij369/scanners-go/releases)
